server:
  port: 8080

spring:
  application:
    name: fintrack-wallet
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fintrack}
    username: ${DB_USER:fintrack}
    password: ${DB_PASSWORD:fintrack}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-123456}
    expiration-minutes: 1440
